/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedFilter: typeof import('./src/components/AdvancedFilter.vue')['default']
    AdvancedFilters: typeof import('./src/components/AdvancedFilters.vue')['default']
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    DeleteEmployeeDialog: typeof import('./src/components/DeleteEmployeeDialog.vue')['default']
    DoughnutChart: typeof import('./src/components/DoughnutChart.vue')['default']
    EmployeeCard: typeof import('./src/components/EmployeeCard.vue')['default']
    EmployeeDashboard: typeof import('./src/components/EmployeeDashboard.vue')['default']
    EmployeeDialog: typeof import('./src/components/EmployeeDialog.vue')['default']
    EmployeeFilters: typeof import('./src/components/EmployeeFilters.vue')['default']
    EmployeeList: typeof import('./src/components/EmployeeList.vue')['default']
    EmployeePublicProfile: typeof import('./src/components/EmployeePublicProfile.vue')['default']
    EmployeeToolbar: typeof import('./src/components/EmployeeToolbar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NumberCard: typeof import('./src/components/NumberCard.vue')['default']
    NumberCardContainer: typeof import('./src/components/NumberCardContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./src/components/Tab.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDataTable: typeof import('vuetify/lib')['VDataTable']
    VDatePicker: typeof import('vuetify/lib')['VDatePicker']
    VerticalTabs: typeof import('./src/components/VerticalTabs.vue')['default']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VRow: typeof import('vuetify/lib')['VRow']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VTextField: typeof import('vuetify/lib')['VTextField']
  }
}
